### ISSUE TITLE
NullPointerException in CodeBuilder - Error handling for CompileException

### ISSUE THREAD

**Issue by WolfgangFahl** [rythmengine/rythmengine#269]
In some cases when the scripting java code taken from a custom resource handler does not compile - then if tryLoadTemplate catches the error and returns a null template class this will lead to a NullPointer Exception.

Error: `java.lang.NullPointerException`
 
null
 
Stacktrace

``` 
java.lang.NullPointerException
	at org.rythmengine.internal.CodeBuilder.addInclude(CodeBuilder.java:540)
	at org.rythmengine.internal.CodeBuilder.addIncludes(CodeBuilder.java:526)
	at org.rythmengine.internal.parser.build_in.IncludeParser$1.go(IncludeParser.java:76)
	at org.rythmengine.internal.parser.ParserDispatcher.go2(ParserDispatcher.java:57)
	at org.rythmengine.internal.TemplateTokenizer$2.next(TemplateTokenizer.java:88)
	at org.rythmengine.internal.TemplateTokenizer$2.next(TemplateTokenizer.java:1)
	at org.rythmengine.internal.TemplateParser.parse(TemplateParser.java:110)
	at org.rythmengine.internal.CodeBuilder.build(CodeBuilder.java:813)
	at org.rythmengine.internal.compiler.TemplateClass.buildSourceCode(TemplateClass.java:479)
	at org.rythmengine.internal.compiler.TemplateClass.refresh(TemplateClass.java:635)
	at org.rythmengine.internal.compiler.TemplateClass.refresh(TemplateClass.java:452)
	at org.rythmengine.internal.compiler.TemplateClass.(TemplateClass.java:344)
	at org.rythmengine.internal.compiler.TemplateClass.(TemplateClass.java:327)
	at org.rythmengine.internal.compiler.TemplateClass.(TemplateClass.java:319)
	at org.rythmengine.RythmEngine.getTemplate(RythmEngine.java:924)
	at org.rythmengine.RythmEngine.getTemplate(RythmEngine.java:947)
	at org.rythmengine.RythmEngine.render(RythmEngine.java:1021)
```

The log shows the error but this way it does not end up in the rendered result and the UI is confronted with the hard to understand NullPointerException above.

The log might e.g. show:
`org.rythmengine.exception.CompileException: topic.sourceTopicLinks.mTopicLinks cannot be resolved to a type`
 
Template: `wiki.SiDIFTemplates.java`
 
Relevant template source lines:
---------------------------------------

It would be nice if the null pointer exception would be avoided but a message be displayed that there is an underlying problem in the include handling.

What should `tryLoadTemplate` do in case of such an error to get proper error reporting in the Render Result/UI?

**Comment by WolfgangFahl** [comment]
I think my pull request fixed this
