### ISSUE TITLE
String index out of range with  followup issues

### ISSUE THREAD

**Issue by WolfgangFahl** [rythmengine/rythmengine#281]
After getting a

error org.rythmengine.exception.ParseException:String index out of range: 12
java.lang.StringIndexOutOfBoundsException: String index out of range: 12
	at java.lang.String.substring(String.java:1950)
	at com.stevesoft.pat.wrap.StringWrap.substring(StringWrap.java:23)
	at com.stevesoft.pat.RegRes.stringMatched(RegRes.java:81)
	at org.rythmengine.internal.Token.stripOuterBrackets(Token.java:222)
	at org.rythmengine.internal.Token.processExtensions(Token.java:301)
	at org.rythmengine.internal.Token.outputExpression(Token.java:272)
	at org.rythmengine.internal.parser.build_in.ExpressionParser$ExpressionToken.output(ExpressionParser.java:99)

The template content is garbled. E.g. a word "topic" is cut to "opic" and than the java compiler complains that "topic" is undefined. 

This might be a fullstop showstopper to I'd be happy to know how to debug this.

**Comment by greenlaw110** [comment]
@WolfgangFahl are you able to provide reproduce steps for this issue report?

**Comment by WolfgangFahl** [comment]
Did not show again

**Comment by WolfgangFahl** [comment]
Too bad happened today: a character was "eaten" on output:

try{pe((etX(combobox.getX()+combobox.get));} catch (RuntimeException e) 

should be
try{pe((getX(combobox.getX()+combobox.get));} catch (RuntimeException e) 

thats really ugly and bad ... and hard to reproduce

**Comment by greenlaw110** [comment]
Need a solid reproduce steps for this ...
