### ISSUE TITLE
NPE captured on TemplateClass.getImportPaths() method

### ISSUE THREAD

**Issue by greenlaw110** [rythmengine/rythmengine#319]
Error stack:

```
java.lang.NullPointerException: null
	at java.util.Collections$UnmodifiableCollection.<init>(Collections.java:1026)
	at java.util.Collections$UnmodifiableSet.<init>(Collections.java:1128)
	at java.util.Collections.unmodifiableSet(Collections.java:1118)
	at org.rythmengine.internal.compiler.TemplateClass.getImportPaths(TemplateClass.java:1077)
	at org.rythmengine.RythmEngine.testTemplate(RythmEngine.java:1521)
	at org.rythmengine.internal.compiler.TemplateClass.refresh_(TemplateClass.java:704)
	at org.rythmengine.internal.compiler.TemplateClass.<init>(TemplateClass.java:444)
	at org.rythmengine.internal.compiler.TemplateClass.<init>(TemplateClass.java:414)
	at org.rythmengine.internal.compiler.TemplateClass.<init>(TemplateClass.java:406)
	at org.rythmengine.RythmEngine.getTemplate(RythmEngine.java:901)
	at org.rythmengine.RythmEngine.getTemplate(RythmEngine.java:924)
	at act.view.rythm.RythmTemplate.template(RythmTemplate.java:46)
        ...
```

**Comment by greenlaw110** [comment]
The workaround literally just avoid NPE by checking the instance. However it needs to investigate the root cause why the `importPaths` field is `null`
