### ISSUE TITLE
jdk1.6 support

### ISSUE THREAD

**Issue by WolfgangFahl** [rythmengine/rythmengine#336]
the pom.xml states source and target 1.6 put mvn test will not run with jdk 1.6
Can we drop 1.6 support for the upcoming release?

```
mvn test
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/apache/maven/cli/MavenCli : Unsupported major.minor version 51.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
    at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClassFromSelf(ClassRealm.java:401)
    at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:42)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:254)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
    at org.codehaus.plexus.classworlds.launcher.Launcher.getMainClass(Launcher.java:144)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:266)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)


```

**Comment by greenlaw110** [comment]
I think this is not a Rythm issue, you are trying to run maven > 3.3 on JDK 1.6, while their page says clearly:

![image](https://cloud.githubusercontent.com/assets/216930/15998461/df38b43e-3181-11e6-94a3-05c42b7c3324.png)

So you are free to use JDK 1.7 or 1.8 to build Rythm, however the generated rythm bytecode file shall be able to be used in a JDK 1.6 environment.

According to [this](https://plumbr.eu/blog/java/java-version-and-vendor-data-analyzed-2016-edition) source, there are still over 9 percent of user are still using Java 1.6. I don't think it's the time we completely drop off 1.6 at the moment

**Comment by WolfgangFahl** [comment]
As you know this bit me again. I have in the meantime upgraded to Ubuntu 16 LTS and my Mac environment is also due to an upgrade. There won't be much JDK 1.6 support left in my environment soon.

**Comment by greenlaw110** [comment]
I have created issue #348 to track the change request. The change in the
code is now landing at feature/348 branch
