### ISSUE TITLE
Templates get compiled with Java 1.8 and are not loadable with rythmengine 1.1.5

### ISSUE THREAD

**Issue by aley2003** [rythmengine/rythmengine#352]
In an programm running on java 1.8 with rythmengine 1.1.5 I get 
`java.lang.UnsupportedClassVersionError: startPage_txt__R_T_C__ : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at org.rythmengine.internal.compiler.TemplateClassLoader.loadTemplateClass(TemplateClassLoader.java:298)
	at org.rythmengine.internal.compiler.TemplateClassLoader.loadClass(TemplateClassLoader.java:254)
	at org.rythmengine.internal.compiler.TemplateClass.loadJavaClass(TemplateClass.java:479)
	at org.rythmengine.internal.compiler.TemplateClass.templateInstance_(TemplateClass.java:492)
	at org.rythmengine.internal.compiler.TemplateClass.asTemplate(TemplateClass.java:520)
	at org.rythmengine.internal.compiler.TemplateClass.asTemplate(TemplateClass.java:526)
	at org.rythmengine.RythmEngine.getTemplate(RythmEngine.java:903)
	at org.rythmengine.RythmEngine.getTemplate(RythmEngine.java:924)
	at org.rythmengine.RythmEngine.render(RythmEngine.java:998)`
I think a template compiled with Java 1.8 can not be loaded by rythmengine compiled with Java 1.7.
In the constructor of class TemplateCompiler there is a check for the java.version property:
`String javaVersion = CompilerOptions.VERSION_1_6;
 String provisionedJavaVersion = System.getProperty("java.version");
 if (provisionedJavaVersion.startsWith("1.7")) {
       javaVersion = CompilerOptions.VERSION_1_7;
 } else if (provisionedJavaVersion.startsWith("1.8")) {
       javaVersion = CompilerOptions.VERSION_1_8;
 }`
I guess setting javaVersion to CompilerOptions.VERSION_1_8 is wrong, because the generated class will not be compatible with the Java 1.7 rythmengine.

**Comment by aley2003** [comment]
Perhaps it only happens, if the program has been started with Java 1.8, templates got compiled and afterwards the programm gets started with Java 1.7.

**Comment by igmar** [comment]
This is a known issue with all Java programs : You cannot load a class compiled with JDK 1.8 on a JDK 1.7 VM.

**Comment by aley2003** [comment]
I know. 

Imagine you have a Java 1.7 programm with rythmengine. 
If you start it with Jre 1.8, it will generate Java 1.8 classes for the templates.
If you start it with Jre 1.7 afterwards, you will get the Exception because of the cached Java 1.8 template classes.
Perhaps it would be better to generate Java 1.8 template classes only as long as rythmengine is Java 1.7 compatible.
