### ISSUE TITLE
Problem with Rythm in sandbox mode under JDK 1.8 + Tomcat 8.5.11

### ISSUE THREAD

**Issue by ashbike** [rythmengine/rythmengine#356]
Trying out Rythm sandbox mode with the following code inside a servlet produces a really long stacktrace. And the stracktrace keeps repeating even without any further servlet call. Runs fine without sandbox. Template is just a single line with no fancy stuff. Any clue? 

Env: java version "1.8.0_111" 64 bit, Tomcat 8.5.11, Rythm 1.1.5 + Commons-lang3 3.3.2 + mvel2 2.1.5 + pat-jar 1.5.3
```
protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		Rythm.init();
		String output = Rythm.render("This is a test");
		response.getWriter().append("Generated: ").append(output);
	}
```
It goes like:
```
SEVERE: Servlet.service() for servlet [a.b.c.TestServlet] in context with path [/template-test] threw exception [Servlet execution threw an exception] with root cause
java.lang.StackOverflowError
	at java.io.FilePermission$1.run(Unknown Source)
	at java.io.FilePermission$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.io.FilePermission.init(Unknown Source)
	at java.io.FilePermission.<init>(Unknown Source)
	at sun.net.www.protocol.file.FileURLConnection.getPermission(Unknown Source)
	at sun.net.www.protocol.jar.JarURLConnection.getPermission(Unknown Source)
	at sun.misc.URLClassPath.check(Unknown Source)
	at sun.misc.URLClassPath$JarLoader.checkResource(Unknown Source)
	at sun.misc.URLClassPath$JarLoader.getResource(Unknown Source)
	at sun.misc.URLClassPath.getResource(Unknown Source)
	at sun.misc.URLClassPath.getResource(Unknown Source)
	at java.lang.ClassLoader.getBootstrapResource(Unknown Source)
	at java.lang.ClassLoader.getResource(Unknown Source)
...
```
Full stacktrace is available at https://dl.dropboxusercontent.com/u/209499/rythm-tomcat-stacktrace.txt

**Comment by greenlaw110** [comment]
You got a `StackOverflowError`. Would like to know what resource it is trying to load. Can you set a breakpoint 

```
	at org.rythmengine.sandbox.RythmSecurityManager.checkPermission(RythmSecurityManager.java:339)
```

And tell me which resource it want to load?

The other problem in your code is you want to init Rythm on `GET` request, absolutely not correct. You should do it when your application loaded, or at least in the `init()` method of your servlet if you have only one servlet across entire application

**Comment by greenlaw110** [comment]
The only real project that uses sandbox I know is https://github.com/rythmengine/rythm-website. Have a look at the source code of this project to get some idea on how to use sandbox mode
