### ISSUE TITLE
Rendering a template with 50k lines takes a long time

### ISSUE THREAD

**Issue by metsmarko** [rythmengine/rythmengine#367]
When I try to render a template which contains about 50k lines (1.1MB) it takes me around 2 hours.
Template itself is rather simple, it contains 1 if statement which contains all the data of the file.

Rythm version: 1.1.5
Below is thread dump of the process (where trace of my code was removed):

```
at com.stevesoft.pat.Regex._search(Regex.java:637)
	at com.stevesoft.pat.Regex._search(Regex.java:622)
	at com.stevesoft.pat.Regex.search(Regex.java:559)
	at org.rythmengine.internal.parser.build_in.NullableExpressionParser$1.go(NullableExpressionParser.java:62)
	at org.rythmengine.internal.parser.ParserDispatcher.go2(ParserDispatcher.java:63)
	at org.rythmengine.internal.TemplateTokenizer$2.next(TemplateTokenizer.java:88)
	at org.rythmengine.internal.TemplateTokenizer$2.next(TemplateTokenizer.java:75)
	at org.rythmengine.internal.TemplateParser.parse(TemplateParser.java:110)
	at org.rythmengine.internal.CodeBuilder.build(CodeBuilder.java:830)
	at org.rythmengine.internal.compiler.TemplateClass.buildSourceCode_(TemplateClass.java:586)
	at org.rythmengine.internal.compiler.TemplateClass.refresh_(TemplateClass.java:741)
	at org.rythmengine.internal.compiler.TemplateClass.<init>(TemplateClass.java:444)
	at org.rythmengine.internal.compiler.TemplateClass.<init>(TemplateClass.java:414)
	at org.rythmengine.internal.compiler.TemplateClass.<init>(TemplateClass.java:406)
	at org.rythmengine.RythmEngine.getTemplate(RythmEngine.java:901)
	at org.rythmengine.RythmEngine.getTemplate(RythmEngine.java:924)
	at org.rythmengine.RythmEngine.render(RythmEngine.java:1046)
```

Is this expected behavior?

**Comment by greenlaw110** [comment]
@metsmarko unfortunately Rythm has serious performance issue with big template file. The workaround is to split the file into multiple small files, e.g. file1, file2, file3, ... and then in your master file, you can do 

```
@file1()
@file2()
@file3()
```

**Comment by metsmarko** [comment]
Thanks!

**Comment by WolfgangFahl** [comment]
I'd recommend that Rythm will issue a warning and propose the split for big files.
