### ISSUE TITLE
Fiddle doesn't work today 2018-12-10

### ISSUE THREAD

**Issue by WolfgangFahl** [rythmengine/rythmengine#382]
http://fiddle.rythmengine.org/
gives an error message: 502 Bad gateway

**Comment by greenlaw110** [comment]
@WolfgangFahl thanks for reporting. I am not sure what happened, when I tried to start rythm fiddle, I got the following error:

```
Compilation error (In /app/models/InMemoryMessageResolver.java around line 61)
        at play.classloading.ApplicationCompiler$2.acceptResult(ApplicationCompiler.java:246)
        at org.eclipse.jdt.internal.compiler.Compiler.handleInternalException(Compiler.java:678)
        at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:522)
        at play.classloading.ApplicationCompiler.compile(ApplicationCompiler.java:282)
        at play.classloading.ApplicationClassloader.getAllClasses(ApplicationClassloader.java:426)
        at play.Play.preCompile(Play.java:593)
        at play.Play.init(Play.java:299)
        at play.server.Server.main(Server.java:159)
```

At the moment I don't have time to go deep into the issue and fix it. 

If you need the product to wrong, try clone https://github.com/rythmengine/rythmfiddle and get it setup on your environment.

**Comment by WolfgangFahl** [comment]
Thanks Green. 
when trying to run the fiddle in my enviroment as per the README.md

`play deps --verbose --sync`

fails with gelinsoft.com not being reachable ...

**Comment by greenlaw110** [comment]
try find out `conf/dependencies.yml` file. Replace `gelinsoft` with `greenlaw110`
